# Generated by Django 4.2.20 on 2025-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_num', models.IntegerField(unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
