# Generated by Django 4.2.20 on 2025-03-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
