# Generated by Django 4.2.20 on 2025-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
