# Generated by Django 4.2.20 on 2025-08-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='txn_ref',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
